'use client'

import { useState } from 'react'
import { DocumentArrowDownIcon, DocumentDuplicateIcon, EyeIcon, SparklesIcon } from '@heroicons/react/24/outline'

const rows=[
 {name:'Erol_Akarsu_Resume_Accenture_Federal_NET_Azure_3_Page_Humanized.pdf',type:'Master resume',job:'General .NET / Azure federal roles',updated:'Today',status:'Verified'},
 {name:'Erol_Akarsu_Accenture_Senior_NET_Azure_AI.pdf',type:'Tailored',job:'Accenture Federal Services',updated:'Today',status:'Ready for review'},
 {name:'Erol_Akarsu_McKesson_Finance_GCP.pdf',type:'Tailored',job:'McKesson Finance Solutions',updated:'Today',status:'Submitted'},
]

export default function ResumesPage(){const [notice,setNotice]=useState('');return <div className="space-y-6"><div className="page-header"><div><h1 className="page-title">Resume library</h1><p className="text-gray-600 mt-1">A master resume supplies verified evidence; every job receives a separately saved version.</p></div><label className="btn-primary cursor-pointer">Upload master resume<input type="file" className="hidden" accept=".pdf,.doc,.docx" onChange={e=>setNotice(e.target.files?.[0]?`${e.target.files[0].name} selected for profile review.`:'')}/></label></div>{notice&&<div className="p-4 bg-blue-50 text-blue-800 rounded-lg">{notice}</div>}<div className="grid md:grid-cols-3 gap-6"><div className="stat-card"><p className="text-sm text-gray-600">Master resumes</p><p className="text-3xl font-bold mt-1">1</p></div><div className="stat-card"><p className="text-sm text-gray-600">Tailored resumes</p><p className="text-3xl font-bold mt-1">2</p></div><div className="stat-card"><p className="text-sm text-gray-600">Claims requiring confirmation</p><p className="text-3xl font-bold text-amber-600 mt-1">0</p></div></div><section className="card p-0 overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr><th className="table-header">Resume</th><th className="table-header">Purpose</th><th className="table-header">Status</th><th className="table-header">Updated</th><th className="table-header">Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.name}><td className="table-cell"><div className="flex items-center gap-3"><DocumentDuplicateIcon className="w-6 h-6 text-primary-600"/><div><p className="font-medium max-w-md break-all">{row.name}</p><p className="text-gray-500">{row.type}</p></div></div></td><td className="table-cell">{row.job}</td><td className="table-cell"><span className={`badge ${row.status==='Submitted'?'badge-success':row.status==='Verified'?'badge-info':'badge-warning'}`}>{row.status}</span></td><td className="table-cell">{row.updated}</td><td className="table-cell"><div className="flex gap-2"><button title="Preview" className="btn-ghost p-2"><EyeIcon className="w-4 h-4"/></button><button title="Download" className="btn-ghost p-2"><DocumentArrowDownIcon className="w-4 h-4"/></button></div></td></tr>)}</tbody></table></div></section><section className="card bg-primary-50 border-primary-200"><div className="flex gap-4"><SparklesIcon className="w-7 h-7 text-primary-700 shrink-0"/><div><h2 className="font-semibold text-primary-900">Tailoring rules</h2><p className="text-primary-900 mt-1">The service can reorder, shorten, and restate verified experience for relevance. New employers, certifications, skills, clearances, dates, and measured results require candidate evidence before use.</p></div></div></section></div>}
