'use client'

import { FormEvent, useEffect, useState } from 'react'
import { CheckCircleIcon } from '@heroicons/react/24/outline'

const initial={firstName:'Erol',lastName:'Akarsu',email:'eakarsu@gmail.com',phone:'',city:'Richmond',state:'VA',country:'United States',linkedin:'linkedin.com/in/erol-akarsu',github:'github.com/eakarsu',citizenship:'U.S. Citizen',sponsorship:'No',clearance:'None',publicTrust:'Eligible',relocate:'Ask for each job',onsite:'Ask for each job',remote:'Yes',salaryMinimum:'',notice:'2 weeks',travel:'Up to 25%',veteran:'No',disability:'Prefer not to answer',gender:'Prefer not to answer',ethnicity:'Prefer not to answer'}

export default function ProfilePage(){const [form,setForm]=useState(initial);const [saved,setSaved]=useState(false);useEffect(()=>{const value=localStorage.getItem('careerflow-profile');if(value)try{setForm({...initial,...JSON.parse(value)})}catch{}},[]);function change(key:string,value:string){setForm(v=>({...v,[key]:value}));setSaved(false)}function submit(e:FormEvent){e.preventDefault();localStorage.setItem('careerflow-profile',JSON.stringify(form));setSaved(true)}const input=(key:keyof typeof initial,label:string,type='text')=><label><span className="label">{label}</span><input className="input" type={type} value={form[key]} onChange={e=>change(key,e.target.value)}/></label>;const select=(key:keyof typeof initial,label:string,options:string[])=><label><span className="label">{label}</span><select className="input" value={form[key]} onChange={e=>change(key,e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>;
return <form onSubmit={submit} className="space-y-6"><div className="page-header"><div><h1 className="page-title">Candidate profile</h1><p className="text-gray-600 mt-1">Reusable answers for job-specific applications. Review sensitive answers before submission.</p></div><button className="btn-primary">Save profile</button></div>{saved&&<div className="p-4 rounded-lg bg-green-50 text-green-800 flex gap-2"><CheckCircleIcon className="w-5 h-5"/>Profile saved in this browser.</div>}
<section className="card"><h2 className="section-title">Identity and contact</h2><div className="grid md:grid-cols-2 gap-4">{input('firstName','Legal first name')}{input('lastName','Legal last name')}{input('email','Email','email')}{input('phone','Phone','tel')}{input('city','City')}{input('state','State')}{input('country','Country')}{input('linkedin','LinkedIn profile')}{input('github','GitHub profile')}</div></section>
<section className="card"><h2 className="section-title">Work eligibility</h2><div className="grid md:grid-cols-2 gap-4">{select('citizenship','Citizenship',['U.S. Citizen','Dual citizen','Permanent resident','Other'])}{select('sponsorship','Require sponsorship now or later?',['No','Yes','Ask me'])}{select('clearance','Current security clearance',['None','Public Trust','Secret','Top Secret','Ask me'])}{select('publicTrust','Public Trust eligibility',['Eligible','Not eligible','Unsure'])}</div></section>
<section className="card"><h2 className="section-title">Job preferences</h2><div className="grid md:grid-cols-2 gap-4">{select('relocate','Relocation',['Ask for each job','Yes','No'])}{select('onsite','On-site work',['Ask for each job','Yes','No'])}{select('remote','Remote work',['Yes','No','Hybrid preferred'])}{input('salaryMinimum','Minimum base salary')}{input('notice','Notice period')}{select('travel','Travel availability',['None','Up to 10%','Up to 25%','Up to 50%','More than 50%'])}</div></section>
<section className="card border-amber-200"><h2 className="section-title">Voluntary self-identification</h2><p className="text-sm text-gray-600 mb-5">These answers are voluntary. The system uses the exact answer you provide and does not infer disability status from a condition such as blindness.</p><div className="grid md:grid-cols-2 gap-4">{select('veteran','Protected veteran status',['No','Yes','Prefer not to answer'])}{select('disability','Disability self-identification',['No, I do not have a disability','Yes, I have a disability or had one in the past','Prefer not to answer'])}{select('gender','Gender',['Male','Female','Non-binary','Prefer not to answer'])}{select('ethnicity','Race or ethnicity',['Prefer not to answer','White','Black or African American','Asian','Hispanic or Latino','American Indian or Alaska Native','Native Hawaiian or Pacific Islander','Two or more races'])}</div></section>
<section className="card"><h2 className="section-title">Resume and history intake</h2><div className="grid md:grid-cols-2 gap-4"><label><span className="label">Master resume</span><input className="input" type="file" accept=".pdf,.doc,.docx"/></label><label><span className="label">Highest degree</span><select className="input" defaultValue="Ph.D."><option>Ph.D.</option><option>Master&apos;s</option><option>Bachelor&apos;s</option></select></label></div><p className="text-sm text-gray-500 mt-4">Employment history, education, certifications, portfolio projects, references, and job-specific screening answers will be reviewed before a live submission.</p></section>
</form>}
