'use client'

import { useMemo, useState } from 'react'
import { jobs, Job } from '@/lib/demo-data'
import { ArrowTopRightOnSquareIcon, CheckCircleIcon, FunnelIcon, SparklesIcon, XMarkIcon } from '@heroicons/react/24/outline'

export default function JobsPage(){
  const [days,setDays]=useState(7); const [query,setQuery]=useState(''); const [source,setSource]=useState('All'); const [selected,setSelected]=useState<Job|null>(null); const [created,setCreated]=useState<string[]>([])
  const filtered=useMemo(()=>jobs.filter(j=>j.postedDays<=days&&(source==='All'||j.source===source)&&`${j.title} ${j.company} ${j.location}`.toLowerCase().includes(query.toLowerCase())),[days,query,source])
  function create(job:Job){setCreated(v=>[...new Set([...v,job.id])]);setSelected(job);localStorage.setItem(`careerflow-application-${job.id}`,JSON.stringify({job,status:'Resume Ready',createdAt:new Date().toISOString()}))}
  return <div className="space-y-6"><div className="page-header"><div><h1 className="page-title">Find recent jobs</h1><p className="text-gray-600 mt-1">Search window and sources apply to every discovery run.</p></div><button className="btn-primary"><SparklesIcon className="w-5 h-5"/>Run job search</button></div>
    <section className="card"><div className="grid md:grid-cols-3 gap-4"><label><span className="label">Keywords or company</span><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Azure, data engineer, McKesson"/></label><label><span className="label">Posted within</span><select className="input" value={days} onChange={e=>setDays(Number(e.target.value))}>{[1,2,3,4,5,6,7].map(d=><option key={d} value={d}>Last {d} day{d>1?'s':''}</option>)}</select></label><label><span className="label">Source</span><select className="input" value={source} onChange={e=>setSource(e.target.value)}>{['All','LinkedIn','Monster','Dice','Company site'].map(s=><option key={s}>{s}</option>)}</select></label></div><div className="mt-4 flex flex-wrap gap-2 text-sm text-gray-600"><FunnelIcon className="w-5 h-5"/><span>Sources: LinkedIn, Monster, Dice, supported ATS and employer career sites</span></div></section>
    <section className="card p-0 overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr><th className="table-header">Role</th><th className="table-header">Source</th><th className="table-header">Posted</th><th className="table-header">Match</th><th className="table-header">Status</th><th className="table-header">Action</th></tr></thead><tbody>{filtered.map(job=><tr key={job.id} className="hover:bg-gray-50 cursor-pointer" onClick={()=>setSelected(job)}><td className="table-cell"><p className="font-medium">{job.title}</p><p className="text-gray-500">{job.company} · {job.location}</p></td><td className="table-cell">{job.source}</td><td className="table-cell">{job.postedDays===1?'Today':`${job.postedDays} days ago`}</td><td className="table-cell"><span className="badge badge-success">{job.match}%</span></td><td className="table-cell">{created.includes(job.id)?<span className="badge badge-info">Resume ready</span>:job.status}</td><td className="table-cell"><button className="btn-ghost text-sm" onClick={e=>{e.stopPropagation();setSelected(job)}}>Review</button></td></tr>)}</tbody></table></div></section>
    {selected&&<div className="fixed inset-0 z-50 bg-slate-950/50 p-4 grid place-items-center" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section role="dialog" aria-modal="true" className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-auto"><header className="p-5 border-b flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{selected.title}</h2><p className="text-gray-600">{selected.company} · {selected.location}</p></div><button aria-label="Close" onClick={()=>setSelected(null)}><XMarkIcon className="w-6 h-6"/></button></header><div className="p-6 space-y-5"><div className="grid grid-cols-2 gap-4"><div><span className="text-xs text-gray-500">Match</span><p className="font-semibold text-green-700">{selected.match}%</p></div><div><span className="text-xs text-gray-500">Compensation</span><p className="font-semibold">{selected.salary}</p></div><div><span className="text-xs text-gray-500">Work mode</span><p>{selected.workMode}</p></div><div><span className="text-xs text-gray-500">Source</span><p>{selected.source}</p></div></div><div><h3 className="font-semibold mb-2">Required qualifications</h3><ul className="list-disc pl-5 text-gray-700 space-y-1">{selected.requirements.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3 className="font-semibold mb-2">Preferred qualifications</h3><ul className="list-disc pl-5 text-gray-700 space-y-1">{selected.preferred.map(x=><li key={x}>{x}</li>)}</ul></div></div><footer className="p-5 border-t flex flex-wrap justify-end gap-3"><button className="btn-ghost" onClick={()=>setSelected(null)}>Cancel</button><button className="btn-secondary"><ArrowTopRightOnSquareIcon className="w-5 h-5"/>Open posting</button><button className="btn-primary" onClick={()=>create(selected)}>{created.includes(selected.id)?<><CheckCircleIcon className="w-5 h-5"/>Application created</>:<><SparklesIcon className="w-5 h-5"/>Tailor resume</>}</button></footer></section></div>}
  </div>
}
