import Link from 'next/link'
import { ArrowRightIcon, CheckIcon, ClipboardDocumentCheckIcon, DocumentTextIcon, MagnifyingGlassIcon, ShieldCheckIcon, SparklesIcon } from '@heroicons/react/24/outline'

const features=[
  {icon:MagnifyingGlassIcon,title:'Fresh job discovery',description:'Search supported boards and employer sites for jobs posted during your selected 1-to-7-day window.'},
  {icon:SparklesIcon,title:'Evidence-based tailoring',description:'Adapt each resume to the job while keeping every claim grounded in verified work history.'},
  {icon:ClipboardDocumentCheckIcon,title:'Resumable applications',description:'Save every application step and continue after MFA, CAPTCHA, assessments, or new questions.'},
  {icon:ShieldCheckIcon,title:'Sensitive answer controls',description:'Reuse work authorization and voluntary disclosure answers only when the candidate has supplied them.'},
  {icon:DocumentTextIcon,title:'Submission ledger',description:'Retain the exact resume, answers, timestamps, and employer confirmation for every application.'},
]

export default function LandingPage(){return <div className="min-h-screen bg-white">
  <header className="fixed inset-x-0 top-0 z-40 border-b bg-white/95 backdrop-blur"><div className="max-w-7xl mx-auto h-16 px-6 flex items-center justify-between"><Link href="/" className="font-bold text-xl flex items-center gap-2"><span className="w-8 h-8 rounded-lg bg-primary-600 text-white grid place-items-center">C</span>CareerFlow AI</Link><nav className="flex items-center gap-6"><a href="#features" className="hidden sm:block text-sm text-gray-600">Features</a><Link href="/dashboard" className="btn-primary">Open workspace</Link></nav></div></header>
  <section className="pt-32 pb-20 px-6"><div className="max-w-5xl mx-auto text-center"><div className="inline-flex items-center gap-2 bg-primary-50 text-primary-700 px-4 py-2 rounded-full text-sm font-medium mb-6"><SparklesIcon className="w-4 h-4"/>Job search and application workspace</div><h1 className="text-5xl sm:text-6xl font-bold leading-tight">Find the right job.<span className="text-primary-600"> Submit the right resume.</span></h1><p className="text-xl text-gray-600 max-w-3xl mx-auto mt-6">Discover recent roles, tailor a verified resume to each posting, complete multistep applications, and keep every submission organized.</p><div className="mt-8 flex justify-center"><Link href="/dashboard" className="btn-primary text-lg px-8 py-4">Open candidate workspace<ArrowRightIcon className="w-5 h-5"/></Link></div></div></section>
  <section className="py-16 bg-gray-50 px-6"><div className="max-w-5xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8">{[['1-7','day search'],['1','resume per job'],['9','tracked steps'],['100%','reviewable']].map(([n,l])=><div className="text-center" key={l}><div className="text-4xl font-bold text-primary-600">{n}</div><div className="text-gray-600">{l}</div></div>)}</div></section>
  <section id="features" className="py-20 px-6"><div className="max-w-7xl mx-auto"><div className="text-center mb-14"><h2 className="text-3xl font-bold">One workspace for the entire application</h2><p className="text-gray-600 text-lg mt-3">Modeled after the proven HomeServ AI dashboard experience.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">{features.map(f=><div className="card hover:shadow-lg transition-shadow" key={f.title}><div className="w-12 h-12 bg-primary-100 rounded-lg grid place-items-center mb-4"><f.icon className="w-6 h-6 text-primary-600"/></div><h3 className="text-xl font-semibold mb-2">{f.title}</h3><p className="text-gray-600">{f.description}</p></div>)}</div><div className="mt-12 card border-primary-200 bg-primary-50"><div className="flex items-start gap-3"><CheckIcon className="w-6 h-6 text-primary-700 shrink-0"/><p className="text-primary-900">Each generated resume and application answer remains linked to the source evidence used to create it.</p></div></div></div></section>
</div>}
